//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace uchebnaya.Components
{
    using System;
    using System.Collections.Generic;
    
    public partial class employee
    {
        public int emp_id { get; set; }
        public string kafedra_shifr { get; set; }
        public string emp_name { get; set; }
        public string emp_position { get; set; }
        public Nullable<int> emp_salary { get; set; }
        public Nullable<int> shef_id { get; set; }
    
        public virtual Kafedra Kafedra { get; set; }
        public virtual engineer engineer { get; set; }
        public virtual zav_kafedri zav_kafedri { get; set; }
    }
}
