//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace uchebnaya.Components
{
    using System;
    using System.Collections.Generic;
    
    public partial class exam
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public exam()
        {
            this.ExamStudent = new HashSet<ExamStudent>();
        }
    
        public int exam_id { get; set; }
        public Nullable<System.DateTime> exam_date { get; set; }
        public Nullable<int> disciplina_id { get; set; }
        public Nullable<int> prepod_id { get; set; }
        public string exam_auditoriya { get; set; }
    
        public virtual disciplina disciplina { get; set; }
        public virtual prepod prepod { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ExamStudent> ExamStudent { get; set; }
    }
}
