//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace uchebnaya.Components
{
    using System;
    using System.Collections.Generic;
    
    public partial class ExamStudent
    {
        public int exam_Stud_id { get; set; }
        public Nullable<int> student_id { get; set; }
        public Nullable<int> exam_ocenka { get; set; }
        public Nullable<int> exam_id { get; set; }
    
        public virtual exam exam { get; set; }
        public virtual student student { get; set; }
    }
}
